// <auto-generated />
using CIT195HonorsProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIT195HonorsProject.Migrations
{
    [DbContext(typeof(CIT195HonorsProjectContext))]
    [Migration("20260425033606_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CIT195HonorsProject.Models.HardDrive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacityGB")
                        .HasColumnType("int");

                    b.Property<bool>("IsSolidState")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NodeClusterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NodeClusterId");

                    b.ToTable("HardDrives");
                });

            modelBuilder.Entity("CIT195HonorsProject.Models.NodeCluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NodeLocation")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("NodeClusters");
                });

            modelBuilder.Entity("CIT195HonorsProject.Models.HardDrive", b =>
                {
                    b.HasOne("CIT195HonorsProject.Models.NodeCluster", "NodeClusters")
                        .WithMany("HardDrives")
                        .HasForeignKey("NodeClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NodeClusters");
                });

            modelBuilder.Entity("CIT195HonorsProject.Models.NodeCluster", b =>
                {
                    b.Navigation("HardDrives");
                });
#pragma warning restore 612, 618
        }
    }
}
